In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
exped_df = pd.read_csv('./data/exped.csv', low_memory=False)
member_df = pd.read_csv('./data/members.csv', low_memory=False)
peak_df = pd.read_csv('./data/peaks.csv', low_memory=False)

In [18]:
exped_df.loc[(exped_df.year == 1981) & (exped_df.host == 'Nepal'), :]

,expid,peakid,year,season,host,route1,route2,route3,route4,nation,...,accidents,achievment,agency,comrte,stdrte,primrte,primmem,primref,primid,chksum
7,ANN281302,ANN2,1981,Autumn,Nepal,NW Ridge-W Ridge,NaN,NaN,NaN,Italy,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2449912
8,ANN281301,ANN2,1981,Autumn,Nepal,S Ridge/SE Face,NaN,NaN,NaN,Japan,...,Icikawa killed by 500m fall at 7400m,NaN,NaN,False,False,False,False,False,NaN,2449930
35,ANN481101,ANN4,1981,Spring,Nepal,NW Ridge,NaN,NaN,NaN,W Germany,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2449761
36,ANN481301,ANN4,1981,Autumn,Nepal,NW Ridge,NaN,NaN,NaN,Italy,...,NaN,NaN,NaN,False,False,True,True,True,ANN281302,2449929
37,ANN481401,ANN4,1981,Winter,Nepal,N Face-NW Ridge,NaN,NaN,NaN,Canada,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2450002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3086,YALU81102,YALU,1981,Spring,Nepal,SE Face,NaN,NaN,NaN,Japan,...,NaN,NaN,NaN,False,False,True,True,True,KANG81101,2448425
3627,ANN181102,ANN1,1981,Spring,Nepal,S Face (E of Bonington rte),NaN,NaN,NaN,Poland,...,NaN,NaN,NaN,False,False,True,True,True,ANNM81101,2449697
3629,CHUL81301,CHUL,1981,Autumn,Nepal,W Ridge,NaN,NaN,NaN,UK,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2450678
3947,GAN681101,GAN6,1981,Spring,Nepal,SE Ridge,NaN,NaN,NaN,Japan,...,NaN,1st ascent of Ganesh VI,NaN,False,False,False,False,True,GAN281101,2447026
9765,TARS81301,TARS,1981,Autumn,Nepal,N Face,NaN,NaN,NaN,Italy,...,NaN,NaN,NaN,False,False,False,False,False,NaN,2450469

In [26]:
member_df.loc[member_df.sex == 'M', :].head(100)

,expid,membid,peakid,myear,mseason,fname,lname,sex,yob,citizen,...,death,deathdate,deathtime,deathtype,deathhgtm,deathclass,msmtbid,msmtterm,hcn,mchksum
0,AMAD01101,2,AMAD,2001,Spring,Rohan,Buckley,M,1972.0,Australia,...,False,NaN,NaN,NaN,0,NaN,No summit bid,Did not climb or intent to summit,NaN,2439554
1,AMAD01101,1,AMAD,2001,Spring,Marc Cameron,Fairhead,M,1968.0,Australia,...,False,NaN,NaN,NaN,0,NaN,Aborted at high camp,"Bad conditions (deep snow, avalanches, falling...",NaN,2438062
2,AMAD01101,3,AMAD,2001,Spring,Mark,Schroeder,M,1960.0,Australia,...,False,NaN,NaN,NaN,0,NaN,Aborted at high camp,"Bad conditions (deep snow, avalanches, falling...",NaN,2435183
3,AMAD01101,4,AMAD,2001,Spring,Colin,Smith,M,1966.0,Australia,...,False,NaN,NaN,NaN,0,NaN,No summit bid,Did not climb or intent to summit,NaN,2437475
5,AMAD01102,1,AMAD,2001,Spring,Sergei,Menchenin,M,1958.0,USA,...,False,NaN,NaN,NaN,0,NaN,No summit bid,"Altitude (AMS symptoms, breathing or unwell)",NaN,2434617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,CHOY01106,3,CHOY,2001,Spring,Michael,Bindig,M,1963.0,Germany,...,False,NaN,NaN,NaN,0,NaN,Unspecified,Unspecified,NaN,2436198
106,CHOY01106,4,CHOY,2001,Spring,Lothar,Dedek,M,1939.0,Germany,...,False,NaN,NaN,NaN,0,NaN,Unspecified,Unspecified,NaN,2427651
107,CHOY01106,5,CHOY,2001,Spring,Hermann,Eisenhans,M,1960.0,Germany,...,False,NaN,NaN,NaN,0,NaN,Aborted above high camp,"Assisting, guiding, supporting or accompanying...",NaN,2435174
108,CHOY01106,6,CHOY,2001,Spring,Albert,Gelhardt,M,1954.0,Germany,...,False,NaN,NaN,NaN,0,NaN,Aborted above high camp,"Frostbite, snowblindness or coldness",NaN,2432903
109,CHOY01106,7,CHOY,2001,Spring,Stefan,Graeff,M,1966.0,Germany,...,False,NaN,NaN,NaN,0,NaN,Aborted above high camp,"Frostbite, snowblindness or coldness",NaN,2437223

In [27]:
peak_df.head(10)

,peakid,pkname,pkname2,location,heightm,heightf,himal,region,open,unlisted,...,phost,pstatus,pyear,pseason,pmonth,pday,pexpid,pcountry,psummiters,psmtnote
0,ACHN,Aichyn,"Aychin, Ashvin",Chandi Himal (SW of Changwathang),6055,19865,Nalakankar/Chandi/Changla,Kanjiroba-Far West,True,False,...,Nepal only,Climbed,2015.0,Autumn,Sep,3.0,ACHN15301,Japan,"Hiroki Senda, et al",NaN
1,AMAD,Ama Dablam,Amai Dablang,Khumbu Himal,6814,22356,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,1961.0,Spring,Mar,13.0,AMAD61101,"New Zealand, USA, UK","Mike Gill, Wally Romanes, Barry Bishop, Michae...",NaN
2,AMOT,Amotsang,Amatson,Damodar Himal (NW of Pokharhan),6393,20974,Damodar,Annapurna-Damodar-Peri,True,False,...,Nepal only,Climbed,2019.0,Autumn,Oct,24.0,AMOT19301,Germany,Jost Kobusch,Possibly climbed earlier
3,AMPG,Amphu Gyabjen,Amphu Gyabien,Khumbu Himal (N of Ama Dablam),5630,18471,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,1953.0,Spring,Apr,11.0,AMPG53101,UK,"John Hunt, Tom Bourdillon",NaN
4,AMPH,Amphu I,NaN,"Khumbu Himal (E of Amphu Laptsa, W of Baruntse)",6740,22113,Khumbu,Khumbu-Rolwaling-Makalu,True,False,...,Nepal only,Climbed,2013.0,Autumn,Oct,9.0,AMPH13301,S Korea,"An Chi-Young, Kim Young-Mi, Oh Young-Hoon",NaN
5,AMPM,Amphu Middle,Amphu North,Khumbu Himal (NW of Amphu Laptsa),6202,20348,Khumbu,Khumbu-Rolwaling-Makalu,False,True,...,Nepal only,Climbed,2008.0,Spring,Apr,20.0,AMPM08101,Germany,"Olaf Rieck, Alexander Graeber",NaN
6,ANID,Anidesh Chuli,White Wave Peak,Kangchenjunga Himal (W of Kangbachen),6808,22336,Kangchenjunga/Simhalila,Kangchenjunga-Janak,True,False,...,Nepal only,Unclimbed,NaN,NaN,NaN,NaN,NaN,NaN,Unclimbed,NaN
7,ANN1,Annapurna I,NaN,Annapurna Himal,8091,26545,Annapurna,Annapurna-Damodar-Peri,True,False,...,Nepal only,Climbed,1950.0,Spring,Jun,3.0,ANN150101,France,"Maurice Herzog, Louis Lachenal",NaN
8,ANN2,Annapurna II,NaN,Annapurna Himal,7937,26040,Annapurna,Annapurna-Damodar-Peri,True,False,...,Nepal only,Climbed,1960.0,Spring,May,17.0,ANN260101,"UK, Nepal","Richard Grant, Chris Bonington, Ang Nyima Sherpa",NaN
9,ANN3,Annapurna III,NaN,Annapurna Himal,7555,24787,Annapurna,Annapurna-Damodar-Peri,True,False,...,Nepal only,Climbed,1961.0,Spring,May,6.0,ANN361101,India,"Mohan S. Kohli, Sonam Gyatso, Sonam Girmi",NaN